"""
OBJ export operator: correct scale (×1000), axis, and OBJ group names
prefixed with Rhino layer names based on jewelry type tags.
Also generates an optional companion RhinoScript.
"""
import bpy
import os
from bpy.types import Operator
from ..properties.props import LAYER_MAP, SKIP_NURBS_CONVERSION


# Layers that should have QuadRemesh → ToSubD → ToNURBS applied in Rhino
def _layers_needing_nurbs(objects):
    """Return the set of Rhino layer names that need NURBS conversion."""
    layers = set()
    for obj in objects:
        tag = obj.rhino_bridge.jewelry_type
        if tag not in SKIP_NURBS_CONVERSION:
            layers.add(LAYER_MAP[tag])
    return layers


def _write_rhino_script(filepath, nurbs_layers):
    """
    Write a companion RhinoScript (.py) that:
    1. Selects all objects on each layer
    2. Runs QuadRemesh → ToSubD → ToNURBS on them
    """
    lines = [
        "# Auto-generated by Bella's Rhino Bridge",
        "# Run this in Rhino via: Tools > PythonScript > Run",
        "import rhinoscriptsyntax as rs",
        "",
        "rs.EnableRedraw(False)",
        "",
    ]

    for layer_name in sorted(nurbs_layers):
        lines += [
            f"# Convert {layer_name} to NURBS",
            f"objs = rs.ObjectsByLayer('{layer_name}')",
            f"if objs:",
            f"    rs.SelectObjects(objs)",
            f"    rs.Command('_QuadRemesh _Enter', echo=False)",
            f"    rs.Command('_ToSubD _Enter', echo=False)",
            f"    rs.Command('_ToNURBS _Enter', echo=False)",
            f"    rs.UnselectAllObjects()",
            "",
        ]

    lines += [
        "rs.EnableRedraw(True)",
        "print('Rhino Bridge: conversion complete.')",
    ]

    with open(filepath, 'w') as f:
        f.write('\n'.join(lines))


def _rename_obj_groups(obj_filepath, objects):
    """
    Post-process the OBJ file: prefix each 'g <name>' line with the
    Rhino layer name so Rhino's 'Import to Layers by Group' works.
    Builds a lookup from Blender object name → prefixed group name.
    """
    name_to_group = {}
    for obj in objects:
        tag = obj.rhino_bridge.jewelry_type
        layer = LAYER_MAP.get(tag, 'Untagged')
        # Rhino-safe name: no spaces
        safe_name = obj.name.replace(' ', '_')
        name_to_group[obj.name] = f"{layer}_{safe_name}"

    if not os.path.exists(obj_filepath):
        return

    with open(obj_filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    new_lines = []
    for line in lines:
        if line.startswith('g '):
            # OBJ group name is typically the Blender object name
            raw_name = line[2:].strip()
            # Try to match to an object (Blender may append _mesh suffix)
            matched = None
            for obj_name, group_name in name_to_group.items():
                if raw_name == obj_name or raw_name.startswith(obj_name):
                    matched = group_name
                    break
            if matched:
                new_lines.append(f"g {matched}\n")
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    with open(obj_filepath, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)


class BRB_OT_ExportOBJ(Operator):
    """Export selected (or all tagged) objects as OBJ for Rhino Matrix Gold"""
    bl_idname = "brb.export_obj"
    bl_label = "Export for Rhino (OBJ)"
    bl_options = {'REGISTER'}

    @classmethod
    def poll(cls, context):
        scene_props = context.scene.rhino_bridge
        return bool(scene_props.export.output_path)

    def execute(self, context):
        scene_props = context.scene.rhino_bridge
        export = scene_props.export

        output_dir = bpy.path.abspath(export.output_path)
        os.makedirs(output_dir, exist_ok=True)

        # Gather export targets
        include_untagged = export.include_untagged
        all_mesh_objs = [o for o in context.scene.objects if o.type == 'MESH']
        targets = [
            o for o in all_mesh_objs
            if include_untagged or o.rhino_bridge.jewelry_type != 'NONE'
        ]

        if not targets:
            self.report({'WARNING'}, "No tagged mesh objects found. Tag objects in the N-panel first.")
            return {'CANCELLED'}

        # Temporarily select only the targets
        original_selection = [o for o in context.selected_objects]
        original_active = context.active_object
        bpy.ops.object.select_all(action='DESELECT')
        for obj in targets:
            obj.select_set(True)
        if targets:
            context.view_layer.objects.active = targets[0]

        export_name = export.export_name or "jewelry_export"
        obj_path = os.path.join(output_dir, f"{export_name}.obj")

        # Detect scene units: if meters, scale ×1000 to get mm for Rhino
        scene = context.scene
        is_meters = scene.unit_settings.length_unit in ('METERS', 'NONE')
        scale = 1000.0 if is_meters else 1.0

        try:
            bpy.ops.export_scene.obj(
                filepath=obj_path,
                use_selection=True,
                global_scale=scale,
                axis_forward='Y',
                axis_up='Z',
                use_smooth_groups=True,
                use_normals=True,
                use_materials=False,
                use_triangles=False,
                group_by_object=True,
                keep_vertex_order=False,
            )
        except Exception as e:
            self.report({'ERROR'}, f"OBJ export failed: {e}")
            return {'CANCELLED'}
        finally:
            # Restore selection
            bpy.ops.object.select_all(action='DESELECT')
            for obj in original_selection:
                obj.select_set(True)
            if original_active:
                context.view_layer.objects.active = original_active

        # Rename OBJ groups to include Rhino layer prefix
        _rename_obj_groups(obj_path, targets)

        saved = [f"{export_name}.obj"]

        # Generate companion RhinoScript
        if export.include_rhino_script:
            nurbs_layers = _layers_needing_nurbs(targets)
            if nurbs_layers:
                script_path = os.path.join(output_dir, f"{export_name}_rhino_setup.py")
                _write_rhino_script(script_path, nurbs_layers)
                saved.append(f"{export_name}_rhino_setup.py")

        self.report({'INFO'}, f"Exported: {', '.join(saved)} → {output_dir}")
        return {'FINISHED'}


def register():
    bpy.utils.register_class(BRB_OT_ExportOBJ)


def unregister():
    bpy.utils.unregister_class(BRB_OT_ExportOBJ)
